Edit fix
SamarthDesai01/RepeatMe pull request #10
Opened 2019-02-14 08:58 UTC by senpl

This makes edit works, tested with limited cases(but with all types)
Code got many duplication with addTask, but I do not know flutter enough to make it more object oriented. Anyway I guess it is functional and could be improved over time. At this time this seems enough. Fix https://github.com/SamarthDesai01/RepeatMe/issues/2 in simple way. Also fix some details in addTasks(like inactive code). All sugestions or discussions are welcomed.

2019-02-14 09:00 UTC, senpl commented
I suggest to change name from "Number" to "No of days" as more descriptive to what actually happens in app.

2019-02-21 07:27 UTC, senpl commented
@SamarthDesai01 any progress with this merge ??? people want this feature.

2019-02-21 16:03 UTC, SamarthDesai01 commented
Hey sorry I didn't get back to you earlier! I've been swamped with work recently, but I'm hoping to take a proper look at it this weekend!

2019-02-25 01:46 UTC, SamarthDesai01 requested changes
The label should read "No. of Days", everything else looks great though!

2019-02-25 01:46 UTC, SamarthDesai01 commented on lib/views/add_task.dart
> +                    label: Text('No of Days'),
Needs to be changed to "No. of Days" to be grammatically correct

2019-02-25 08:11 UTC, senpl commented on lib/views/add_task.dart
> +                    label: Text('No of Days'),
I updated add_task and edit_task to "No. of Days". Commits below.

2019-02-26 20:02 UTC, merged